[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Petter"]
license = "MIT"

[workspace.dependencies]
logos = "0.15"
chumsky = "0.9"
ariadne = "0.4"
thiserror = "2"
once_cell = "1.19"
stacker = "0.1"
